GET http://localhost:3004

###

POST http://localhost:3004
content-type: application/json

{
    "n":"migs",
    "p":"wigs"
}
###

// get token
POST http://localhost:3004/login
content-type: application/json

{
    "n":"migs",
    "p":"wigs"
}


###
// check token -> make sure to get a new token before using this:
get http://localhost:3004/prot
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Im5hbWUiOiJtaWdzIiwiaWQiOjF9LCJpYXQiOjE2NzAyMjI5NzgsImV4cCI6MTY3MDIyMjk4MX0.cqd6mQoWTwiaOeBubWE-H_Uv9dfihd7WZLYr3fcf0-w

###
post http://localhost:3004/updateCount
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Im5hbWUiOiJtaWdzIiwiaWQiOjF9LCJpYXQiOjE2NzAyMjUxMzIsImV4cCI6MTY3MDI0NjczMn0.PzHr7CcilG6oDJVFIUyow4xWaiUzk15JOBXnBSL_GBM


###
POST http://localhost:3004/login
content-type: application/json

{
    "n":"a",
    "p":"a"
}

###
post http://localhost:3004/updateCount
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Im5hbWUiOiJhIiwiaWQiOjJ9LCJpYXQiOjE2NzAyMjYxNjcsImV4cCI6MTY3MDI0Nzc2N30.-5AGWjVIXgUEapzIt8qVvNZ05Z8kCCAkliYL8BvAf_U

{
    "id":1,
    "count": 14
}